# Generated by Django 2.2 on 2020-12-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_name', models.CharField(max_length=32)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Book')),
            ],
        ),
    ]
